### ISSUE TITLE
Add search functionality

### ISSUE THREAD

**Issue by isabisa** [unitymakesus/unity-team-handbook#6]
We can use Algolia (like Jigsaw and Tailwind docs): https://www.algolia.com/

It looks like the Jigsaw docs template includes some boilerplate integration with Algolia too (according to this MD file: https://github.com/tighten/jigsaw-site/blob/main/source/docs/starter-templates.md)

**Comment by andrewmarino** [comment]
https://github.com/algolia/docsearch

**Comment by andrewmarino** [comment]
https://github.com/unitymakesus/unity-team-handbook/commit/b02f53504ce34f49f1753b601989b5676ab593af
